name : Hello Pipeline
on: 
 push: 
  branches: [ "reliase" ]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Saluto
        run: echo "Inizio Workshop CD/CDI"
      - name: Info Sistema
        run: uname-a 